In [27]:
"""ATTENTION:

This notebook relies on the cleaned english data after running clean_english_dataset.py. The only prerequisite is that the data doesn't have invalid or non-english tokens.
"""
import pandas as pd
import nltk
import numpy as np
import os
from gensim.corpora import Dictionary
from gensim.models import LdaMulticore
from gensim.parsing.preprocessing import STOPWORDS
from gensim.test.utils import datapath, get_tmpfile
from gensim.utils import simple_preprocess, lemmatize

### Load data for story content and their tags
#### Note: Load data from the google drive link: https://drive.google.com/drive/u/0/folders/1vfCX_Zlnx1YyL_1uDBK6ZA6mdBPLUpaV

In [4]:
def print_rows(matrix, n_rows=5):
    for i in range(n_rows):
        print(matrix[i])
        
def pos_tokenize_document(doc):
    tokens = simple_preprocess(doc)
    # lemmatizes, POS tags and remove stopwords (including empty strings) from the tokens list for stories
    pos_tokens = [lemmatize(t) for t in tokens if t not in STOPWORDS and len(t)>0]
    # flatten the list-of-lists of POS tokens created by previous operation and return
    return [word for inner_list in pos_tokens for word in inner_list]
    
    
def get_noun_and_adjective(doc):
    pos_tokens = pos_tokenize_document(doc)
    NOUNS = ['NN', 'NNS', 'NNP', 'NNPS']
    ADJECTIVES = ['JJ', 'JJR', 'JJS']
    word_pos_tuples = [token.decode('utf-8').split('/') for token in pos_tokens]
    return_words = [word for word, pos in word_pos_tuples if pos in NOUNS+ADJECTIVES]
    return return_words

In [5]:
DATA_DIR = "../../data/raw/"
DATA_FILE = "stories_content_english_corrected.csv"
TAGS_FILE = "stories_tags_all.csv"

words = set(nltk.corpus.words.words())
# load stories-data and drop those rows where story_content or story_publishing_type are NaN
stories_data = pd.read_csv(DATA_DIR + DATA_FILE).dropna(subset=['story_content', 'story_publishing_type'])
# load tag-data and drop those rows where tags are NaN
tags_data = pd.read_csv(DATA_DIR + TAGS_FILE).dropna(subset=['story_tag_name','story_id'])

publisher_stories_data = stories_data.loc[stories_data['story_publishing_type'] == 'Publisher Story']
non_publisher_stories_data = stories_data.loc[stories_data['story_publishing_type'] != 'Publisher Story']

publisher_tags_data = tags_data[tags_data['story_id'].isin(publisher_stories_data['story_id'])]
non_publisher_tags_data = tags_data[tags_data['story_id'].isin(non_publisher_stories_data['story_id'])]

N_TOTAL_STORIES = len(stories_data)
N_PUBLISHER_STORIES = len(publisher_stories_data)
N_NON_PUBLISHER_STORIES = len(non_publisher_stories_data)
N_TAG_ROWS = len(tags_data)
DF_TAG_LABEL = 'story_tag_name'

print("Total stories: ", N_TOTAL_STORIES)
print("Publisher stories: ", N_PUBLISHER_STORIES)
print("Non-publisher stories: ", N_NON_PUBLISHER_STORIES)
print("Tags rows in tags-file: ", N_TAG_ROWS)

publisher_stories_data.iloc[0]['story_content']

Total stories:  2026
Publisher stories:  311
Non-publisher stories:  1715
Tags rows in tags-file:  35092

"A fawn was racing in the forest. He was ahead of the rabbit. He was ahead of the elephant. He leapt and cleared the stream. He ran past the crumbling wall. There was a large boulder on the grassy plain. He stumbled and fell down. He burst into tears. The monkey massaged his leg. Tears flowed from the fawn's eyes. Brother Bear picked him up. The fawn didn't stop crying. His mother came. She said, “Look, we’ll beat up this bad boulder!” The fawn said, “Oh, don’t do that or he will also start crying.” His mother laughed. So did the fawn."

### We will use non-publisher stories for training, and publisher stories for validation testing

In [6]:
#TODO: expand apostrophe words
all_stories_data = pd.concat([non_publisher_stories_data, publisher_stories_data], axis=0)
all_tokens_data = []

for i in range(len(all_stories_data)):
    row = get_noun_and_adjective(all_stories_data.iloc[i]['story_content'])
    all_tokens_data.append(row)
    
print_rows(all_tokens_data, 2)
print(len(all_tokens_data))

['dog', 'bird', 'dog', 'man', 'bird', 'man', 'swell', 'anger', 'poor', 'bird', 'lesson', 'lesson', 'understood', 'chasing', 'bird', 'good', 'dog']
['gulli', 'grandpa', 'able', 'newspaper', 'glass', 'gulli', 'run', 'little', 'brown', 'box', 'thing', 'clink', 'clonk', 'dadum', 'dum', 'glass', 'bigger', 'gulli', 'grandpa', 'newspaper', 'gulli', 'uncle', 'mangal', 'chacha', 'trouble', 'kitchen', 'pour', 'oil', 'pack', 'bottle', 'neck', 'small', 'clink', 'clonk', 'dadum', 'dum', 'gulli', 'time', 'big', 'wide', 'mouth', 'pour', 'drop', 'drop', 'mangal', 'chacha', 'thank', 'gulli', 'gulli', 'grandma', 'able', 'grandpa', 'monkey', 'cap', 'needle', 'floor', 'clink', 'clonk', 'dadum', 'dum', 'time', 'magnet', 'metal', 'stick', 'grandma', 'needle', 'stick', 'magnet', 'metal', 'thing', 'stick', 'grandma', 'monkey', 'cap', 'isn', 'gulli', 'brown', 'box', 'thing', 'nice']
2026

In [29]:
## Story data
train_data = all_tokens_data[:N_NON_PUBLISHER_STORIES]
test_data = all_tokens_data[N_NON_PUBLISHER_STORIES:]

## Story-ids
train_story_ids = non_publisher_stories_data['story_id'].replace('', np.nan).dropna()
test_story_ids = publisher_stories_data['story_id'].replace('', np.nan).dropna()


#Use training data to build the dictionary for LDA model
id2word = Dictionary(train_data)
print(id2word)

train_data_bow = [id2word.doc2bow(doc) for doc in train_data]
test_data_bow = [id2word.doc2bow(doc) for doc in test_data]

##Save the dictionary too
DICTIONARY_FILE_LOCATION = "../../data/id2word_dictionary"
OS_PATH_TO_DICTIONARY_FILE = os.path.abspath(os.path.join(os.getcwd(), DICTIONARY_FILE_LOCATION))

id2word.save_as_text(datapath(OS_PATH_TO_DICTIONARY_FILE))

Dictionary(12253 unique tokens: ['anger', 'bird', 'chasing', 'dog', 'good']...)

In [8]:

print(len(train_data_bow))
print(len(test_data_bow))
print(train_data_bow[:1])

1715
311
[[(0, 1), (1, 4), (2, 1), (3, 3), (4, 1), (5, 2), (6, 2), (7, 1), (8, 1), (9, 1)]]

In [9]:
story_tags_dict = {}
tag_set = set()  # set of all unique tags in the dataset
tag_count = {}   # number of count for each tag
for story_id in all_stories_data['story_id']:
    tag_list = tags_data['story_tag_name'].loc[tags_data['story_id'] == story_id]
    if(len(tag_list) == 0):
        continue #didn't have tags for this story, so go to next story
    tag_list = [tag.replace('#','').lower() for tag in tag_list if (type(tag) == str and tag not in STOPWORDS)]
    story_tags_dict[story_id] = set(tag_list)
    
    #Update global tag variables (tag_count )
    for tag in tag_list:
        if tag not in tag_count:
            tag_count[tag] = 1
        else:
            tag_count[tag] += 1
    tag_set |= set(tag_list)
    
n_stories_with_tags = len(story_tags_dict)
n_tags_freq_more_than_5 = len([tag for tag in tag_count if tag_count[tag] >= 5])
n_tags_freq_more_than_10 = len([tag for tag in tag_count if tag_count[tag] >= 10])
n_tags_freq_more_than_15 = len([tag for tag in tag_count if tag_count[tag] >= 15])
n_tags_freq_more_than_20 = len([tag for tag in tag_count if tag_count[tag] >= 20])

print("Number of stories with tags: ", n_stories_with_tags)
print("Number of unique tags: ", len(tag_set))
print("Number of Tags occuring 5 times or more: ", n_tags_freq_more_than_5)
print("Number of Tags occuring 10 times or more: ", n_tags_freq_more_than_10)
print("Number of Tags occuring 15 times or more: ", n_tags_freq_more_than_15)
print("Number of Tags occuring 20 times or more: ", n_tags_freq_more_than_20)

Number of stories with tags:  1273
Number of unique tags:  2565
Number of Tags occuring 5 times or more:  256
Number of Tags occuring 10 times or more:  92
Number of Tags occuring 15 times or more:  50
Number of Tags occuring 20 times or more:  35

In [10]:
test_story_id_to_tags = {}

print(publisher_tags_data.columns)
for idx in test_story_ids:
#     print(idx, publisher_tags_data.loc[publisher_tags_data['story_id'] == idx][DF_TAG_LABEL])
    test_story_id_to_tags[idx] = publisher_tags_data.loc[publisher_tags_data['story_id'] == idx][DF_TAG_LABEL]
test_story_id_to_tags

Index(['story_id', 'story_title', 'story_english_title', 'story_tag_name'], dtype='object')

{2: Series([], Name: story_tag_name, dtype: object),
 7: Series([], Name: story_tag_name, dtype: object),
 16: Series([], Name: story_tag_name, dtype: object),
 21: Series([], Name: story_tag_name, dtype: object),
 33: Series([], Name: story_tag_name, dtype: object),
 38: Series([], Name: story_tag_name, dtype: object),
 40: Series([], Name: story_tag_name, dtype: object),
 49: Series([], Name: story_tag_name, dtype: object),
 54: Series([], Name: story_tag_name, dtype: object),
 61: Series([], Name: story_tag_name, dtype: object),
 67: Series([], Name: story_tag_name, dtype: object),
 71: Series([], Name: story_tag_name, dtype: object),
 80: Series([], Name: story_tag_name, dtype: object),
 82: Series([], Name: story_tag_name, dtype: object),
 86: Series([], Name: story_tag_name, dtype: object),
 88: Series([], Name: story_tag_name, dtype: object),
 89: Series([], Name: story_tag_name, dtype: object),
 90: Series([], Name: story_tag_name, dtype: object),
 94: Series([], Name: story_tag_name, dtype: object),
 98: Series([], Name: story_tag_name, dtype: object),
 111: Series([], Name: story_tag_name, dtype: object),
 122: Series([], Name: story_tag_name, dtype: object),
 127: Series([], Name: story_tag_name, dtype: object),
 132: Series([], Name: story_tag_name, dtype: object),
 137: Series([], Name: story_tag_name, dtype: object),
 140: Series([], Name: story_tag_name, dtype: object),
 141: Series([], Name: story_tag_name, dtype: object),
 144: Series([], Name: story_tag_name, dtype: object),
 149: Series([], Name: story_tag_name, dtype: object),
 153: Series([], Name: story_tag_name, dtype: object),
 156: Series([], Name: story_tag_name, dtype: object),
 160: Series([], Name: story_tag_name, dtype: object),
 163: Series([], Name: story_tag_name, dtype: object),
 167: Series([], Name: story_tag_name, dtype: object),
 169: Series([], Name: story_tag_name, dtype: object),
 173: Series([], Name: story_tag_name, dtype: object),
 180: Series([], Name: story_tag_name, dtype: object),
 182: Series([], Name: story_tag_name, dtype: object),
 184: Series([], Name: story_tag_name, dtype: object),
 187: Series([], Name: story_tag_name, dtype: object),
 188: Series([], Name: story_tag_name, dtype: object),
 189: Series([], Name: story_tag_name, dtype: object),
 191: 235    What Shall I Wear Today?
 236                     clothes
 237                    decision
 238                      choice
 239                     fashion
 240                    costumes
 241                    garments
 242                       dress
 Name: story_tag_name, dtype: object,
 196: Series([], Name: story_tag_name, dtype: object),
 202: Series([], Name: story_tag_name, dtype: object),
 207: Series([], Name: story_tag_name, dtype: object),
 208: Series([], Name: story_tag_name, dtype: object),
 209: Series([], Name: story_tag_name, dtype: object),
 212: Series([], Name: story_tag_name, dtype: object),
 218: Series([], Name: story_tag_name, dtype: object),
 234: Series([], Name: story_tag_name, dtype: object),
 240: Series([], Name: story_tag_name, dtype: object),
 245: 297    Rhino Charge
 298          animal
 299          forest
 300          jungle
 301          nature
 302     environment
 303            wild
 304        wildlife
 Name: story_tag_name, dtype: object,
 250: Series([], Name: story_tag_name, dtype: object),
 254: Series([], Name: story_tag_name, dtype: object),
 258: Series([], Name: story_tag_name, dtype: object),
 269: Series([], Name: story_tag_name, dtype: object),
 270: Series([], Name: story_tag_name, dtype: object),
 272: Series([], Name: story_tag_name, dtype: object),
 276: Series([], Name: story_tag_name, dtype: object),
 283: Series([], Name: story_tag_name, dtype: object),
 288: Series([], Name: story_tag_name, dtype: object),
 296: Series([], Name: story_tag_name, dtype: object),
 332: Series([], Name: story_tag_name, dtype: object),
 346: Series([], Name: story_tag_name, dtype: object),
 355: Series([], Name: story_tag_name, dtype: object),
 356: Series([], Name: story_tag_name, dtype: object),
 360: 393        Delhi
 394    transport
 395         auto
 Name: story_tag_name, dtype: object,
 369: Series([], Name: story_tag_name, dtype: object),
 375: Series([], Name: story_tag_name, dtype: object),
 376: Series([], Name: story_tag_name, dtype: object),
 396: Series([], Name: story_tag_name, dtype: object),
 405: 431    Chulbul's Tail
 432           chulbul
 433              tail
 434       self esteem
 435        confidence
 436       life skills
 437            growth
 438            belief
 439        body image
 440        Acceptance
 441            animal
 442           fantasy
 443            doctor
 444           surgery
 Name: story_tag_name, dtype: object,
 409: Series([], Name: story_tag_name, dtype: object),
 415: 451                       dragonflies
 452                       damselflies
 453                            nature
 454                           insects
 455                       environment
 456    From Submarines to Sky Raiders
 Name: story_tag_name, dtype: object,
 453: Series([], Name: story_tag_name, dtype: object),
 462: Series([], Name: story_tag_name, dtype: object),
 470: Series([], Name: story_tag_name, dtype: object),
 486: Series([], Name: story_tag_name, dtype: object),
 628: Series([], Name: story_tag_name, dtype: object),
 633: Series([], Name: story_tag_name, dtype: object),
 638: Series([], Name: story_tag_name, dtype: object),
 646: 618     South America
 619               fox
 620          wildlife
 621            nature
 622    animal stories
 623         folktales
 Name: story_tag_name, dtype: object,
 652: Series([], Name: story_tag_name, dtype: object),
 660: Series([], Name: story_tag_name, dtype: object),
 664: Series([], Name: story_tag_name, dtype: object),
 678: Series([], Name: story_tag_name, dtype: object),
 684: Series([], Name: story_tag_name, dtype: object),
 691: Series([], Name: story_tag_name, dtype: object),
 696: Series([], Name: story_tag_name, dtype: object),
 702: Series([], Name: story_tag_name, dtype: object),
 705: Series([], Name: story_tag_name, dtype: object),
 709: Series([], Name: story_tag_name, dtype: object),
 723: Series([], Name: story_tag_name, dtype: object),
 749: Series([], Name: story_tag_name, dtype: object),
 754: Series([], Name: story_tag_name, dtype: object),
 758: Series([], Name: story_tag_name, dtype: object),
 768: Series([], Name: story_tag_name, dtype: object),
 776: Series([], Name: story_tag_name, dtype: object),
 790: Series([], Name: story_tag_name, dtype: object),
 821: Series([], Name: story_tag_name, dtype: object),
 822: Series([], Name: story_tag_name, dtype: object),
 839: Series([], Name: story_tag_name, dtype: object),
 847: Series([], Name: story_tag_name, dtype: object),
 859: Series([], Name: story_tag_name, dtype: object),
 876: Series([], Name: story_tag_name, dtype: object),
 880: Series([], Name: story_tag_name, dtype: object),
 921: Series([], Name: story_tag_name, dtype: object),
 927: Series([], Name: story_tag_name, dtype: object),
 934: Series([], Name: story_tag_name, dtype: object),
 944: Series([], Name: story_tag_name, dtype: object),
 946: Series([], Name: story_tag_name, dtype: object),
 952: Series([], Name: story_tag_name, dtype: object),
 957: Series([], Name: story_tag_name, dtype: object),
 959: Series([], Name: story_tag_name, dtype: object),
 968: Series([], Name: story_tag_name, dtype: object),
 981: Series([], Name: story_tag_name, dtype: object),
 986: Series([], Name: story_tag_name, dtype: object),
 991: Series([], Name: story_tag_name, dtype: object),
 997: Series([], Name: story_tag_name, dtype: object),
 1002: Series([], Name: story_tag_name, dtype: object),
 1017: Series([], Name: story_tag_name, dtype: object),
 1024: Series([], Name: story_tag_name, dtype: object),
 1029: Series([], Name: story_tag_name, dtype: object),
 1034: Series([], Name: story_tag_name, dtype: object),
 1042: Series([], Name: story_tag_name, dtype: object),
 1052: Series([], Name: story_tag_name, dtype: object),
 1057: Series([], Name: story_tag_name, dtype: object),
 1062: Series([], Name: story_tag_name, dtype: object),
 1067: Series([], Name: story_tag_name, dtype: object),
 1091: Series([], Name: story_tag_name, dtype: object),
 1101: 912               jungle
 913               forest
 914                 bird
 915    The Elephant Bird
 916             elephant
 917              village
 918                horse
 919             children
 920                 girl
 921                magic
 922                Giant
 923              feather
 924                 lake
 925          herbivorous
 926              extinct
 Name: story_tag_name, dtype: object,
 1106: 987    folktale
 988      Norway
 989       funny
 990      farmer
 991         cow
 992     foolish
 993        wise
 994    marriage
 995      couple
 Name: story_tag_name, dtype: object,
 1112: Series([], Name: story_tag_name, dtype: object),
 1121: Series([], Name: story_tag_name, dtype: object),
 1205: Series([], Name: story_tag_name, dtype: object),
 1208: Series([], Name: story_tag_name, dtype: object),
 1219: Series([], Name: story_tag_name, dtype: object),
 1233: Series([], Name: story_tag_name, dtype: object),
 1261: Series([], Name: story_tag_name, dtype: object),
 1278: Series([], Name: story_tag_name, dtype: object),
 1281: Series([], Name: story_tag_name, dtype: object),
 1591: Series([], Name: story_tag_name, dtype: object),
 1658: Series([], Name: story_tag_name, dtype: object),
 1912: Series([], Name: story_tag_name, dtype: object),
 2171: Series([], Name: story_tag_name, dtype: object),
 2380: Series([], Name: story_tag_name, dtype: object),
 2711: Series([], Name: story_tag_name, dtype: object),
 3266: Series([], Name: story_tag_name, dtype: object),
 3566: 1392    STEM
 Name: story_tag_name, dtype: object,
 3625: 1399           bees
 1400           STEM
 1401           buzz
 1402         nature
 1403    environment
 Name: story_tag_name, dtype: object,
 3687: Series([], Name: story_tag_name, dtype: object),
 3787: Series([], Name: story_tag_name, dtype: object),
 3841: 1441      poori
 1442       Puff
 1443    cooking
 1444       STEM
 1445      dough
 Name: story_tag_name, dtype: object,
 3905: 1455    STEM
 Name: story_tag_name, dtype: object,
 4084: Series([], Name: story_tag_name, dtype: object),
 4314: 1618    STEM
 Name: story_tag_name, dtype: object,
 4407: 1644    STEM
 Name: story_tag_name, dtype: object,
 4628: 1685    STEM
 Name: story_tag_name, dtype: object,
 4772: 1714    STEM
 Name: story_tag_name, dtype: object,
 4782: 1716    Artificial Intelligence
 1717                     robots
 1718                 innovation
 1719                 futuristic
 1720                       STEM
 Name: story_tag_name, dtype: object,
 4938: 1747    STEM
 Name: story_tag_name, dtype: object,
 4991: 1784    STEM
 Name: story_tag_name, dtype: object,
 5041: 1798    STEM
 Name: story_tag_name, dtype: object,
 5052: 1808    STEM
 Name: story_tag_name, dtype: object,
 5144: 1902    STEM
 Name: story_tag_name, dtype: object,
 5205: 1957    STEM
 Name: story_tag_name, dtype: object,
 5287: 2020    STEM
 Name: story_tag_name, dtype: object,
 5398: 2129              STEM
 2130            nature
 2131       environment
 2132    climate change
 2133    Sustainability
 2134      conservation
 Name: story_tag_name, dtype: object,
 5619: 2288                  STEM
 2289               pattern
 2290                nature
 2291    Fibonacci sequence
 2292                  math
 Name: story_tag_name, dtype: object,
 5699: 2363                 STEM
 2364    Logical Reasoning
 2365               Riddle
 2366                  Age
 2367              history
 2368               family
 2369               Mysore
 2370                 math
 Name: story_tag_name, dtype: object,
 6100: 2669      bath
 2670     night
 2671     water
 2672    family
 Name: story_tag_name, dtype: object,
 6147: 2709                   garden
 2710                     tree
 2711                    plant
 2712                   nature
 2713                  weather
 2714    #6FrameStoryChallenge
 Name: story_tag_name, dtype: object,
 6818: 3114    friends
 3115     street
 3116    animals
 3117        zoo
 3118       play
 Name: story_tag_name, dtype: object,
 6887: 3132            city
 3133         stories
 3134    storytelling
 Name: story_tag_name, dtype: object,
 7263: 3432               brushing
 3433                hygiene
 3434                 family
 3435                  teeth
 3436                  germs
 3437            Cleanliness
 3438               siblings
 3439    Brushing is No Fun!
 Name: story_tag_name, dtype: object,
 7710: 3583    The Boink Mystery
 3584        jantar mantar
 3585          observatory
 3586              Science
 3587           laboratory
 3588          Cleanliness
 3589              yontrik
 3590                Alien
 3591               gadget
 3592                dirty
 3593               planet
 3594              sundial
 3595              hygiene
 Name: story_tag_name, dtype: object,
 8028: 3793    Avani and the Pea Plant
 3794                       bird
 3795                      mynah
 3796                  earthworm
 3797                       girl
 3798                      woman
 3799                   daughter
 3800                     mother
 3801                        cat
 3802                     garden
 Name: story_tag_name, dtype: object,
 8040: 3805     colours
 3806      street
 3807        blue
 3808         red
 3809    chillies
 3810      purple
 3811     brinjal
 3812      yellow
 3813       lemon
 3814      chuski
 3815        pink
 3816       white
 3817       kulfi
 3818       green
 3819    jaljeera
 3820       brown
 3821       dates
 3822      guavas
 Name: story_tag_name, dtype: object,
 8175: 3859    A Perfect Match
 3860        Competition
 3861               game
 3862              sport
 3863             hockey
 3864      sportsmanship
 3865             spirit
 3866           children
 3867               team
 3868        grandmother
 3869        grandfather
 3870                dog
 3871              funny
 3872                fun
 3873         excitement
 3874        cheerleader
 Name: story_tag_name, dtype: object,
 8218: 3924        Recommended by CBSE
 3925                       hunt
 3926    Sam's Christmas Present
 3927                       gift
 3928                        box
 3929                  Christmas
 3930                    parents
 3931                    curious
 3932                     search
 Name: story_tag_name, dtype: object,
 8223: 3937    Sringeri Srinivas Learns to Laugh
 3938                             laughter
 3939                                  Joy
 3940                                  fun
 3941                                funny
 3942                                anger
 3943                                 fury
 3944                              grumble
 3945                               monkey
 3946                                  man
 3947                               banana
 3948                                 peel
 3949                              harvest
 3950                               farmer
 3951                              village
 3952                                chase
 3953                             mischief
 Name: story_tag_name, dtype: object,
 8594: 4343          Serpy
 4344      the Snake
 4345           Crab
 4346         spider
 4347          birds
 4348           deer
 4349           fawn
 4350           fish
 4351           frog
 4352           walk
 4353            fly
 4354           gait
 4355        slither
 4356       straight
 4357     Acceptance
 4358    self esteem
 4359          lines
 4360         forest
 4361        animals
 Name: story_tag_name, dtype: object,
 8712: 4513    Hatchu! Ha-aaa-tchu!
 4514                  sneeze
 4515                    loud
 4516                 trouble
 4517                   funny
 4518                dramatic
 4519                 village
 4520                  lesson
 4521                   noise
 4522                   scare
 4523                  afraid
 4524                   sound
 Name: story_tag_name, dtype: object,
 8828: 4685                Maaloo
 4686    Kaaloo ...and who?
 4687           grandmother
 4688                   dog
 4689                   boy
 4690                garden
 4691                sounds
 4692             adventure
 4693               mystery
 4694                 ghost
 4695                  bear
 4696                 funny
 4697                 hills
 4698                family
 4699             detective
 4700                  bees
 4701                search
 4702               pursuit
 4703                  clue
 Name: story_tag_name, dtype: object,
 8881: 4777    Turtle Story
 4778         turtles
 4779        tortoise
 4780            eggs
 4781         nesting
 4782       migrating
 4783           ocean
 4784         journey
 4785         species
 4786         animals
 4787          babies
 4788      underwater
 4789          marine
 4790            reef
 4791        survival
 Name: story_tag_name, dtype: object,
 8905: 4804    Chipko Takes Root
 4805             movement
 4806              protest
 4807                trees
 4808         conservation
 4809             greenery
 4810               nature
 4811        deforestation
 4812         preservation
 4813                 girl
 4814            innocence
 4815                fight
 4816           dedication
 4817        determination
 4818                rural
 4819              village
 4820                hills
 4821           landslides
 4822              mankind
 4823               lesson
 4824               ethics
 4825              sadness
 4826              tragedy
 4827             handicap
 4828             crutches
 4829                river
 Name: story_tag_name, dtype: object,
 8907: 4830           Pambaram
 4831    the Naughty Top
 4832                top
 4833                toy
 4834            naughty
 4835              prank
 4836        mischevious
 4837           children
 4838                fun
 4839               play
 4840              games
 4841              chase
 4842             family
 Name: story_tag_name, dtype: object,
 9009: 4937    Why is Nita Upside Down?
 4938                     friends
 4939                  body image
 4940                 self esteem
 4941                    positive
 4942                  Friendship
 4943                  fitting in
 4944                   different
 4945                   Diversity
 4946                    children
 4947                        play
 Name: story_tag_name, dtype: object,
 9388: 5270    One Summer Afternoon
 5271                   death
 5272                    life
 5273                  lesson
 5274                  nature
 5275                   birds
 5276                 naughty
 5277                children
 5278                  millet
 5279                    farm
 5280                  family
 5281                   crane
 5282                   Saras
 Name: story_tag_name, dtype: object,
 9817: 5845    Mr. Anand has an Adventure
 5846                      dinosaur
 5847                          lost
 5848                      creature
 5849                         Alien
 5850                         space
 5851                       planets
 5852                       fantasy
 5853                           old
 5854                          aged
 5855                           man
 5856                     adventure
 5857                        thrill
 5858                        search
 5859                       pursuit
 5860                      language
 5861                          help
 5862                      kindness
 5863                        friend
 5864                        travel
 5865                        flight
 5866                           fly

## LDA model : 50 topics

In [20]:
PRETRAINED_MODEL_FILE_LOCATION = "../models/lda_model"
OS_PATH_TO_MODEL_FILE = os.path.abspath(os.path.join(os.getcwd(), PRETRAINED_MODEL_FILE_LOCATION))
print(OS_PATH_TO_MODEL_FILE)

ldamodel_topics_50 = None
try:
    print("Using pretrained model...")
    ldamodel_topics_50 = LdaMulticore.load(PRETRAINED_MODEL_FILE_LOCATION)
except:
    print("ERORR: Pretrained model not found. Training the model now...")
    ldamodel_topics_50 = LdaMulticore(train_data_bow, num_topics=50, id2word=id2word, passes=20, workers=2)
    ##Save this for future use
    print("\nSaving the trained model to location " + OS_PATH_TO_MODEL_FILE)
    ldamodel_topics_50.save(datapath(OS_PATH_TO_MODEL_FILE))

/Users/goelakas/goelakash/pratham_data/data_v3/PrathamBooks-Sprint-2018/python/models/lda_model
Using pretrained model...

In [21]:
topic_predictions = [ldamodel_topics_50[bow] for bow in test_data_bow]
print(len(topic_predictions))
print(len(test_story_ids))

story_id_to_topic_predictions = {}
for i in range(len(test_story_ids)):
    story_id = test_story_ids.get(i)
    topic = topic_predictions[i]
    story_id_to_topic_predictions[story_id] = topic

311
311

In [23]:
predicted_story_id_to_tags = {}

for story_id, pred in story_id_to_topic_predictions.items():
    word_to_proba = {}
    for topic_id, t_proba in pred:
        topic_words = ldamodel_topics_50.show_topic(topic_id)
        for word, w_proba in topic_words:
            if word not in word_to_proba.keys():
                word_to_proba[word] = 0.0
            word_to_proba[word] += t_proba*w_proba
    ranked_words_and_prob = sorted(word_to_proba.items(), key=lambda kv: kv[1], reverse=True)
    ranked_words = [word_tuple[0] for word_tuple in ranked_words_and_prob]
    predicted_story_id_to_tags[story_id] = ranked_words[:10]

In [24]:
def write_to_csv(dict_predictions):
    with open('predictions.csv', 'w') as output:
        output.write(','.join(['story_id'] + ['tag'+str(i) for i in range(1,11)])+'\n')
        for k,v in dict_predictions.items():
            output.write(','.join([str(k)]+v[:10])+'\n')
        output.close()

write_to_csv(predicted_story_id_to_tags)